[board]
layout = "US QWERTY"
default_board = 0

[ui]
key_font_size = 0.2
mark_font_size = 0.2
emoji_font_size = 0.56
emoji_font_size2 = 0.8

[[layout]]
name = "US QWERTY"
char = "ðŸ‡ºðŸ‡¸"
kbd = """
`1234567890-=
QWERTYUIOP[]\
ASDFGHJKL;'"
ZXCVBNM,./
"""

[[layout]]
name = "DE QWERTZ"
char = "ðŸ‡©ðŸ‡ª"
kbd = """
1234567890ÃŸÂ´
QWERTZUIOPÃœ+
ASDFGHJKLÃ–Ã„#
<YXCVBNM,.-
"""

[[layout]]
name = "Bone Corne"
char = "ðŸ¦´"
kbd = """
JDUAX PHLMW
CTIEO BNRSG
?,VFQ YKZ.-
"""

[sources]
noto_color_emoji = "https://github.com/google/fonts/raw/refs/heads/main/ofl/notocoloremoji/NotoColorEmoji-Regular.ttf"
openmoji = "https://raw.githubusercontent.com/hfg-gmuend/openmoji/refs/heads/master/data/openmoji.csv"
unicode_data = "https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt"

[logging]
log_file = ".local/emojikbd.log"
log_level = "INFO"
