[board]
# one from below layouts
layout = "DE"
# by emoji, e.g. "", "âŸ²", "ğŸ”", "ğŸ˜€", "ğŸ‘ï¸", ...
default = "âŸ²"

[terminal]
width = 47
height = 12
font_size = 20
# receives the emoji as stdin and hides terminal
close_cmd = "./scripts/emoji-kbd-term-hl-close"

[gui]
# in px
width = 600
height = 280
# in % of key size which is derived from window size above
key_font_size = 0.2
mark_font_size = 0.2
emoji_font_size = 0.56
emoji_font_size2 = 0.8


[[layout]]
name = "US"
char = "ğŸ‡ºğŸ‡¸"
kbd = """
1234567890-=
QWERTYUIOP[]
ASDFGHJKL;'
ZXCVBNM,./
"""

[[layout]]
name = "DE"
char = "ğŸ‡©ğŸ‡ª"
kbd = """
1234567890ÃŸÂ´
QWERTZUIOPÃœ+
ASDFGHJKLÃ–Ã„#
<YXCVBNM,.-
"""

[[layout]]
name = "Bone Corne"
char = "ğŸ¦´"
kbd = """
JDUAX PHLMW
CTIEO BNRSG
?,VFQ YKZ.-
"""

[sources]
noto_color_emoji = "https://github.com/google/fonts/raw/refs/heads/main/ofl/notocoloremoji/NotoColorEmoji-Regular.ttf"
openmoji = "https://raw.githubusercontent.com/hfg-gmuend/openmoji/refs/heads/master/data/openmoji.csv"
unicode_data = "https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt"


[logging]
log_mode = "w"
log_level = "INFO"
