[board]
# one from below layouts
layout = "US"
# by emoji, e.g. "", "âŸ²", "ğŸ”", "ğŸ˜€", "ğŸ‘ï¸", ...
default = "âŸ²"
# check emojibase and unicode_annotations links in [sources] for available ones
locale = "en"

[terminal]
width = 47
height = 12
font_size = 20
# receives the emoji as stdin and hides terminal
close_cmd = "./scripts/emoji-kbd-term-hl-close"

[gui]
# in px
width = 600
height = 280
# in % of key size which is derived from window size above
key_font_size = 0.2
mark_font_size = 0.2
emoji_font_size = 0.56
emoji_font_size2 = 0.8


[[layout]]
name = "US"
char = "ğŸ‡ºğŸ‡¸"
kbd = """
1234567890-=
QWERTYUIOP[]
ASDFGHJKL;'
ZXCVBNM,./
"""

[[layout]]
name = "DE"
char = "ğŸ‡©ğŸ‡ª"
kbd = """
1234567890ÃŸÂ´
QWERTZUIOPÃœ+
ASDFGHJKLÃ–Ã„#
<YXCVBNM,.-
"""

[[layout]]
name = "Bone Corne"
char = "ğŸ¦´"
kbd = """
JDUAX PHLMW
CTIEO BNRSG
?,VFQ YKZ.-
"""

[[layout]]
name = "Test"
char = "ğŸ”¬"
kbd = """
 2 45678 0ÃŸ 
QWE TZU OPÃœ+
A DF H KLÃ–  
"""

[sources]
noto_color_emoji = "https://github.com/googlefonts/noto-emoji/raw/refs/heads/main/fonts/NotoColorEmoji.ttf"
noto_color_emoji_win32 = "https://github.com/googlefonts/noto-emoji/raw/refs/heads/main/fonts/NotoColorEmoji_WindowsCompatible.ttf"
emojibase = "https://github.com/milesj/emojibase/raw/refs/heads/master/packages/data"
unicode_data = "https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt"
unicode_annotations = "https://raw.githubusercontent.com/unicode-org/cldr/refs/heads/main/common/annotations/"

[logging]
log_mode = "w"
log_level = "INFO"
